-- MySQL Script generated by MySQL Workbench
-- Wed Aug  9 18:29:59 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`tipo` (
  `id_tipo` INT NOT NULL,
  `descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`id_tipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id_usuario` INT NOT NULL,
  `senha` VARCHAR(100) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `perfil` VARCHAR(130) NOT NULL,
  PRIMARY KEY (`id_usuario`),
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cardapio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cardapio` (
  `id_cardapio` INT NOT NULL,
  `nome_prato` VARCHAR(150) NOT NULL,
  `tempo_praparo` VARCHAR(150) NOT NULL,
  `descricao_prato` VARCHAR(200) NOT NULL,
  `valor_prato` FLOAT NOT NULL,
  `img_prato` LONGBLOB NOT NULL,
  `usuario_id_usuario` INT NOT NULL,
  `categoria` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id_cardapio`),
  INDEX `fk_cardapio_usuario1_idx` (`usuario_id_usuario` ASC),
  CONSTRAINT `fk_cardapio_usuario1`
    FOREIGN KEY (`usuario_id_usuario`)
    REFERENCES `mydb`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;